<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <form action="recap.php" method="POST">
        <input type="text" placeholder="Nom" name="lastname"/>
        <input type="text" placeholder="Prénom" name="firstname"/>
        <input type="text" placeholder="Email" name="email"/>
        <input type="text" placeholder="Adresse" name="address"/>
        <input type="text" placeholder="Ville" name="city"/>
        <input type="submit" value="Envoyer"/>
    </form>


    
</body>
</html>

