<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <div>

        <nav>

            <a href="index.php">Home</a>
            <a href="form.php">lien vers le formulaire</a>
            <a href="get.php?name=Paul&id=32">lien vers le get de Paul</a>
            <a href="get.php?name=Jacques&id=14">lien vers le get de Jacques</a>
            <a href="get.php?name=Pierre&id=39">lien vers le get de Pierre</a>

        </nav>

        <p> Je suis le header</p>	

    </div>
    
</body>
</html>

