<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/index.css">
    <title>Bon de commande</title>
</head>
<body>
    <header>
        <div class="container">
            <h1>Bons de Commande</h1>
            <a href="index.php">retourner a l'acceuil</a>
        </div>
    </header>

    <div class="container">
        <div class="customer">
            <h1> 
                <?= $customer['customerName'] ?>
            </h1>
            <h2>
                <?= $customer['contactLastName'] ?> <?= $customer['contactFirstName'] ?>
            </h2>
            <p>
                <?= $customer['addressLine1'] ?>
            </p>
            <p>
                <?= $customer['city'] ?>
            </p>
        </div>
    </div>
    <div class="clear"></div>
    <div class="container">
        <hr>
    </div>

    <div class="container">
            <table>
                <tr>
                    <th>Produit</th>
                    <th>Prix unitaire</th>
                    <th>Quantité</th>
                    <th>Prix total</th>
                </tr>
                
                <?php foreach ($details as $detail): ?>
                <tr>
                    <td> 
                    <?= $detail['productName'] ?>
                    </td>    
            
                    <td> 
                        <?= round($detail['priceEach'], 2) ?>$   
                    </td>      
   
                    <td> 
                        <?= $detail['quantityOrdered'] ?>    
                    </td>

                    <td> 
                        <?= round($detail['totalPrice'], 2) ?>$
                    </td>
                </tr>
                <?php endforeach ?>

                <?php foreach ($totals as $total): ?>
                <tr>
                    <td style="text-align: right;" colspan="3">Montant total HT </td>
                    <td style="text-align: right;" colspan="4"> 
                        <?= round($total['total']) ?>$
                    </td>  
                </tr>

                <tr>    
                    <td style="text-align: right;" colspan="3">TVA (20%)</td>
                    <td style="text-align: right;" colspan="4"> 
                        <?= round($total['total'] * 0.2) ?>$
                    </td> 
                </tr>

                <tr>    
                    <td style="text-align: right;" colspan="3">Prix total TTC</td>
                    <td style="text-align: right;" colspan="4"> 
                        <?= round($total['total'] + $total['total'] * 0.2) ?>$
                    </td> 
                </tr>
                <?php endforeach ?>
                
            </table>
        </div>

</body>
</html>