<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/index.css">
    <title>Document</title>
</head>
<body>

    <header class="header">
        <nav class="header_nav">
            <ul class="header_nav_ul">
                <li><a href="index.php">Acceuil</a></li>

                <?php if($_SESSION == null): ?>
                    <li><a href="register.php">Register</a></li>
                    <li><a href="login.php">Login</a></li>
                <?php endif ?>
                
                <?php if(array_key_exists('firstName', $_SESSION)): ?>
                    <li><a href="destroy.php">Logout</a></li>
                <?php endif ?>
                
            </ul>
        </nav>
    </header>

    <main class="main">
            
        <?php include $template.'.phtml' ?>
        
    </main>

    <footer>Copyright</footer>
</body>
</html>

