<div class="main">

    <form class="main_form" action="register.php" method="POST">
        
        <label>Nom</label>
        <input type="text" name="lastName" placeholder="Votre Nom">

        <label>Prénom</label>
        <input type="text" name="firstName" placeholder="Votre prénom">

        <label>Age</label>
        <input type="text" name="age" placeholder="Votre age">

        <label>Mail</label>
        <input type="mail" name="email" placeholder="Votre mail">

        <label>Mot de passe</label>
        <input type="password" name="password" placeholder="Saisissez un mot de passe">

        <button type="submit">Envoyer</button>
    </form>

</div>