<form class="register_form"action ="register.php" method="POST">
    <fieldset>
        <legend><h2>Inscription</h2></legend>

        <div class="register_form_content">
            <input type="text" placeholder="Prénom" name="firstName">
            <input type="text" placeholder="Nom" name="lastName">
            <input type="text" placeholder="Pseudo" name="nickName">
            <input type="text" placeholder="@Mail" name="email">
            <input type="password" placeholder="password" name="psw">
        </div>

            <input type="submit" value="Valider"/>
    </fieldset>
</form>